### ISSUE TITLE
Jupyterlite kernel fails to launch

### ISSUE THREAD

**Issue by LeoGrin** [skrub-data/skrub#752] opened 2023-09-25 16:09 UTC
### Describe the bug

I cannot run the Skrub examples using Jupyterlite (https://skrub-data.org/stable/lite/lab/) (#625 #633). It's stuck on the first cell I try to run, and the kernel status is shown as  "Unknown".

Not sure if this is related, but the rendering doesn't work either: 
<img width="1017" alt="image" src="https://github.com/skrub-data/skrub/assets/45738728/a4d0721a-de22-4727-b06d-752cdce298a0">

### Steps/Code to Reproduce

Go to https://skrub-data.org/stable/lite/lab/ and try to run an example. I would like to see if other people are having the same issue (for me scikit-learn's examples are working).

### Expected Results

The examples can be run on jupyterlite.

### Actual Results

Kernel status "Unknown", notebook stuck on the first cell execution.

### Versions

```shell
MacOS 12.6.5
Google Chrome Version 117.0.5938.88 (Official Build) (arm64)
```

**Comment by Vincent-Maladiere** [comment] 2023-09-27 08:37
Thanks for spotting, @LeoGrin. I can reproduce your error. Upon opening a jupyterlite notebook, the service fails at importing micropip (you can see it in the web console)
```red
Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 540, in eval_code_async
    await CodeRunner(
  File "/lib/python311.zip/_pyodide/_base.py", line 365, in run_async
    await coroutine
  File "<exec>", line 4, in <module>
  File "/lib/python3.11/site-packages/piplite/__init__.py", line 2, in <module>
    from .piplite import install
  File "/lib/python3.11/site-packages/piplite/piplite.py", line 16, in <module>
    from micropip.package_index import ProjectInfo
ModuleNotFoundError: No module named 'micropip.package_index'
```
This is probably an issue with jupyterlite (or maybe with its interface with sphinx), I'll post an issue on jupyterlite.

**Comment by glemaitre** [comment] 2023-09-27 10:09
> Not sure if this is related, but the rendering doesn't work either:

The rendering is something different and linked to RST but we cannot do much about it.

**Comment by lesteve** [comment] 2023-09-27 12:56
Not 100% sure, but this could be an issue of generating the stable doc with an old version of jupyterlite and a new Pyodide version having to been released. 

Maybe you want a jupyterlite-json like on your stable branch, https://github.com/skrub-data/skrub/blob/main/doc/jupyter-lite.json so that it happens less?

**Comment by psychemedia** [comment] 2023-10-05 10:50
I'm not seeing any kernels at all installed in your jupyterlite instance? (In recent versions of jupyterlite, I think you need to install a kernel explicitly when building jupyterlite)

<img width="890" alt="image" src="https://github.com/skrub-data/skrub/assets/82988/ffe5a729-5bd8-4dac-95d3-44c38c8fa777">

**Comment by jeromedockes** [comment] 2024-07-01 12:43
jupyterlite seems to be working for me now on the stable and dev branch. I have a question for @glemaitre : we have in the doc configuration the URL of the wheel to install [here](https://github.com/skrub-data/skrub/blob/37db0ab6da45a88b2ab48a7e73b45e7573a36cdb/doc/conf.py#L381) (at the moment it uses 0.0.1)

does this mean after a release we need to update this url, rebuild the doc & push to the stable branch?

**Comment by GaelVaroquaux** [comment] 2024-07-01 13:06
I checked, and it does work now. Thanks!! and hurray!!

**Comment by jeromedockes** [comment] 2024-07-01 13:21
> I checked, and it does work now.

cool :) I think that if @lesteve 's suspicion above was right, it probably started working back in December when we did the 0.1.0 release and thus the `stable` doc was built with the `jupyter-lite.json` file added by @glemaitre -- we just didn't realize and close the issue

**Closed by jeromedockes** 2024-07-01 13:21 UTC
Labels: bug
