### ISSUE TITLE
TableReport fails with `np.inf`

### ISSUE THREAD

**Issue by Vincent-Maladiere** [skrub-data/skrub#1134] opened 2024-11-07 23:37 UTC
### Describe the bug

`np.inf` values raise a `ValueError` in `TableReport`. Maybe we should count them and display them along with the nulls as well?

### Steps/Code to Reproduce

```python
import pandas as pd
import numpy as np
from skrub import TableReport

TableReport(pd.DataFrame(dict(a=[np.inf, 1])))
```

### Expected Results

No errors

### Actual Results

<details><summary>Traceback</summary>

```
ValueError                                Traceback (most recent call last)
File ~/dev/finit/data-risks/.venv/lib/python3.12/site-packages/IPython/core/formatters.py:347, in BaseFormatter.__call__(self, obj)
    345     method = get_real_method(obj, self.print_method)
    346     if method is not None:
--> 347         return method()
    348     return None
    349 else:

File ~/dev/inria/skrub/skrub/_reporting/_table_report.py:190, in TableReport._repr_html_(self)
    189 def _repr_html_(self):
--> 190     return self._repr_mimebundle_()[\"text/html\"]

File ~/dev/inria/skrub/skrub/_reporting/_table_report.py:187, in TableReport._repr_mimebundle_(***failed resolving arguments***)
    185 def _repr_mimebundle_(self, include=None, exclude=None):
    186     del include, exclude
--> 187     return {\"text/html\": self.html_snippet()}

File ~/dev/inria/skrub/skrub/_reporting/_table_report.py:166, in TableReport.html_snippet(self)
    157 def html_snippet(self):
    158     \"\"\"Get the report as an HTML fragment that can be inserted in a page.
    159 
    160     Returns
   (...)
    163         The HTML snippet.
    164     \"\"\"
    165     return to_html(
--> 166         self._summary_with_plots,
    167         standalone=False,
    168         column_filters=self.column_filters,
    169     )

File /opt/homebrew/Cellar/python@3.12/3.12.7/Frameworks/Python.framework/Versions/3.12/lib/python3.12/functools.py:993, in cached_property.__get__(self, instance, owner)
    991 val = cache.get(self.attrname, _NOT_FOUND)
    992 if val is _NOT_FOUND:
--> 993     val = self.func(instance)
    994     try:
    995         cache[self.attrname] = val

File ~/dev/inria/skrub/skrub/_reporting/_table_report.py:127, in TableReport._summary_with_plots(self)
    125 @functools.cached_property
    126 def _summary_with_plots(self):
--> 127     return summarize_dataframe(
    128         self.dataframe, with_plots=True, title=self.title, **self._summary_kwargs
    129     )

File ~/dev/inria/skrub/skrub/_reporting/_summarize.py:83, in summarize_dataframe(df, order_by, with_plots, title, max_top_slice_size, max_bottom_slice_size)
     78 for position in range(sbd.shape(df)[1]):
     79     print(
     80         f\"Processing column {position + 1: >3} / {n_columns}\", end=\"\\r\", flush=True
     81     )
     82     summary[\"columns\"].append(
---> 83         _summarize_column(
     84             sbd.col_by_idx(df, position),
     85             position,
     86             dataframe_summary=summary,
     87             with_plots=with_plots,
     88             order_by_column=order_by_column,
     89         )
     90     )
     91 print(flush=True)
     92 summary[\"n_constant_columns\"] = sum(
     93     c[\"value_is_constant\"] for c in summary[\"columns\"]
     94 )

File ~/dev/inria/skrub/skrub/_reporting/_summarize.py:136, in _summarize_column(column, position, dataframe_summary, with_plots, order_by_column)
    132     return summary
    133 _add_value_counts(
    134     summary, column, dataframe_summary=dataframe_summary, with_plots=with_plots
    135 )
--> 136 _add_numeric_summary(
    137     summary,
    138     column,
    139     dataframe_summary=dataframe_summary,
    140     with_plots=with_plots,
    141     order_by_column=order_by_column,
    142 )
    143 _add_datetime_summary(summary, column, with_plots=with_plots)
    144 summary[\"plot_names\"] = [k for k in summary.keys() if k.endswith(\"_plot\")]

File ~/dev/inria/skrub/skrub/_reporting/_summarize.py:227, in _add_numeric_summary(***failed resolving arguments***)
    225     return
    226 if order_by_column is None:
--> 227     summary[\"histogram_plot\"] = _plotting.histogram(
    228         column, color=_plotting.COLORS[0]
    229     )
    230 else:
    231     summary[\"line_plot\"] = _plotting.line(order_by_column, column)

File ~/dev/inria/skrub/skrub/_reporting/_plotting.py:61, in _plot.<locals>.plot_with_config(*args, **kwargs)
     57 warnings.filterwarnings(\"ignore\", \"Glyph.*missing from font\")
     58 warnings.filterwarnings(
     59     \"ignore\", \"Matplotlib currently does not support Arabic natively\"
     60 )
---> 61 return plotting_fun(*args, **kwargs)

File ~/dev/inria/skrub/skrub/_reporting/_plotting.py:124, in histogram(col, color)
    122 fig, ax = plt.subplots()
    123 _despine(ax)
--> 124 ax.hist(values, color=color)
    125 if sbd.is_any_date(col):
    126     _rotate_ticklabels(ax)

File ~/dev/finit/data-risks/.venv/lib/python3.12/site-packages/matplotlib/__init__.py:1473, in _preprocess_data.<locals>.inner(ax, data, *args, **kwargs)
   1470 @functools.wraps(func)
   1471 def inner(ax, *args, data=None, **kwargs):
   1472     if data is None:
-> 1473         return func(
   1474             ax,
   1475             *map(sanitize_sequence, args),
   1476             **{k: sanitize_sequence(v) for k, v in kwargs.items()})
   1478     bound = new_sig.bind(ax, *args, **kwargs)
   1479     auto_label = (bound.arguments.get(label_namer)
   1480                   or bound.kwargs.get(label_namer))

File ~/dev/finit/data-risks/.venv/lib/python3.12/site-packages/matplotlib/axes/_axes.py:7001, in Axes.hist(self, x, bins, range, density, weights, cumulative, bottom, histtype, align, orientation, rwidth, log, color, label, stacked, **kwargs)
   6997 # Loop through datasets
   6998 for i in range(nx):
   6999     # this will automatically overwrite bins,
   7000     # so that each histogram uses the same bins
-> 7001     m, bins = np.histogram(x[i], bins, weights=w[i], **hist_kwargs)
   7002     tops.append(m)
   7003 tops = np.array(tops, float)  # causes problems later if it's an int

File ~/dev/finit/data-risks/.venv/lib/python3.12/site-packages/numpy/lib/histograms.py:780, in histogram(a, bins, range, density, weights)
    680 r\"\"\"
    681 Compute the histogram of a dataset.
    682 
   (...)
    776 
    777 \"\"\"
    778 a, weights = _ravel_and_check_weights(a, weights)
--> 780 bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)
    782 # Histogram is an integer or a float array depending on the weights.
    783 if weights is None:

File ~/dev/finit/data-risks/.venv/lib/python3.12/site-packages/numpy/lib/histograms.py:426, in _get_bin_edges(a, bins, range, weights)
    423     if n_equal_bins < 1:
    424         raise ValueError('`bins` must be positive, when an integer')
--> 426     first_edge, last_edge = _get_outer_edges(a, range)
    428 elif np.ndim(bins) == 1:
    429     bin_edges = np.asarray(bins)

File ~/dev/finit/data-risks/.venv/lib/python3.12/site-packages/numpy/lib/histograms.py:315, in _get_outer_edges(a, range)
    312         raise ValueError(
    313             'max must be larger than min in range parameter.')
    314     if not (np.isfinite(first_edge) and np.isfinite(last_edge)):
--> 315         raise ValueError(
    316             \"supplied range of [{}, {}] is not finite\".format(first_edge, last_edge))
    317 elif a.size == 0:
    318     # handle empty arrays. Can't determine range, so use 0-1.
    319     first_edge, last_edge = 0, 1

ValueError: supplied range of [1.0, inf] is not finite"
```

</details>

### Versions

```shell
dev
```

**Comment by jeromedockes** [comment] 2024-11-08 08:10
I'll close this as a duplicate of #1133

**Comment by jeromedockes** [comment] 2024-11-08 08:11
ah no actually looking at the traceback it's another issue, this one in the plotting of the histogram -- reopening

**Comment by jeromedockes** [comment] 2024-11-08 08:13
yes also reporting the number of infinite values also sounds useful

**Closed** 2024-11-22 08:52 UTC
Labels: bug
