### ISSUE TITLE
Should accept pipelines and transformers

### ISSUE THREAD

**Issue by koaning** [skrub-data/skrub#904] opened 2024-05-13 15:51 UTC
### Describe the bug

I was passing a pipeline to a table vectorizer via something like this:

```python
TableVectorizer(datetime_transformer=time_pipe)
```

But this breaks. 

```
    raise ValueError(
ValueError: 'transformer' must be an instance of sklearn.base.TransformerMixin, 'remainder' or 'passthrough'. Got transformer=Pipeline(steps=[('selectcols', SelectCols(cols='date')),
                ('functiontransformer',
                 FunctionTransformer(func=<function datetime_feats at 0x1377ea0c0>)),
                ('splinetransformer',
                 SplineTransformer(extrapolation='periodic', n_knots=12))])
```

### Steps/Code to Reproduce

```python
from sklearn.preprocessing import FunctionTransformer
from sklearn.pipeline import make_pipeline
from skrub import TableVectorizer

TableVectorizer(datetime_transformer=make_pipeline(FunctionTransformer()))
```

Now try and fit some data against it. 

### Expected Results

No error is thrown. 

### Actual Results

Error is mentioned earlier

### Versions

```shell
skrub version 0.1.0
```

**Comment by jeromedockes** [comment] 2024-05-13 15:58
thanks! this is a duplicate of #886
it will be fixed by #902

**Closed** 2024-05-13 16:02 UTC
Labels: bug
