### ISSUE TITLE
Add `packaging` as a required dependency?

### ISSUE THREAD

**Issue by baggiponte** [skrub-data/skrub#698] opened 2023-08-18 08:26 UTC
### Describe the bug

Whenever you import `skrub` you get this warning:

```
/private/tmp/test/.venv/lib/python3.10/site-packages/skrub/__init__.py:13: UserWarning: packaging is not available, dependencies versions will not be checked.
  warnings.warn(
```

### Steps/Code to Reproduce

```sh
virtualenv .venv

source .venv/bin/activate

pip install git+https://github.com/skrub-data/skrub.git

python -c "import skrub"
```

### Expected Results

No error is thrown

### Actual Results

/private/tmp/test/.venv/lib/python3.10/site-packages/skrub/__init__.py:13: UserWarning: packaging is not available, dependencies versions will not be checked.
  warnings.warn(

### Versions

```shell
python -c "import sklearn, skrub; sklearn.show_versions(); print(skrub.__version__);"
/private/tmp/test/.venv/lib/python3.10/site-packages/skrub/__init__.py:13: UserWarning: packaging is not available, dependencies versions will not be checked.
  warnings.warn(

System:
    python: 3.10.12 (main, Jul 18 2023, 16:20:24) [Clang 14.0.3 (clang-1403.0.22.14.1)]
executable: /private/tmp/test/.venv/bin/python
   machine: macOS-13.3-arm64-arm-64bit

Python dependencies:
      sklearn: 1.3.0
          pip: 23.2.1
   setuptools: 68.0.0
        numpy: 1.25.2
        scipy: 1.11.2
       Cython: None
       pandas: 2.0.3
   matplotlib: None
       joblib: 1.3.2
threadpoolctl: 3.2.0

Built with OpenMP: True

threadpoolctl info:
       user_api: openmp
   internal_api: openmp
    num_threads: 8
         prefix: libomp
       filepath: /private/tmp/test/.venv/lib/python3.10/site-packages/sklearn/.dylibs/libomp.dylib
        version: None

       user_api: blas
   internal_api: openblas
    num_threads: 8
         prefix: libopenblas
       filepath: /private/tmp/test/.venv/lib/python3.10/site-packages/numpy/.dylibs/libopenblas64_.0.dylib
        version: 0.3.23.dev
threading_layer: pthreads
   architecture: armv8

       user_api: blas
   internal_api: openblas
    num_threads: 8
         prefix: libopenblas
       filepath: /private/tmp/test/.venv/lib/python3.10/site-packages/scipy/.dylibs/libopenblas.0.dylib
        version: 0.3.21.dev
threading_layer: pthreads
   architecture: armv8
0.0.1.dev0
```

**Comment by fcharras** [comment] 2023-08-21 13:00
The bug was introduced in https://github.com/skrub-data/skrub/pull/648

@jeremiedbb apparently  `packaging` only comes pre-installed with pip when using the conda distribution, otherwise it must be installed explicitly. 

In this regard #648 seems like a regression should it be reverted, or still resorting to the `package_resources` way of doing is `packaging` is not found at least ?

`package_resources` has the disadvantage of outputting another warning because direct usage is discouraged, but in this particular case outside of conda distribution it's still the only native package with what is needed to check the dependency tree at runtime it seems.

The possible outcomes I see there would be either

- add `packaging` as a dependency of skrub
- fallback on the `package_resources` solution if packaging is not importable
- revert #648

**Comment by Vincent-Maladiere** [comment] 2023-08-25 11:45
Thank you @baggiponte and @fcharras for the investigation! Closing this as #712 fixes the issue.

**Closed by Vincent-Maladiere** 2023-08-25 11:45 UTC
Labels: bug
